Background:
android.hardware.radio.data was frozen in the upstream tm-dev.
Previously, the interface had only V1 (as the in-development version)
and it was in the VNDK. However, after the freeze, it will have V1 and
V2, and only V1 will remain in the VNDK, because we can't have multiple
versions of the same AIDL interface in VNDK.

Problem:
```
> error: hardware/interfaces/radio/aidl/Android.bp:225:1: module "android.hardware
.radio.ims.media-V1-ndk" variant "android_vendor.Tiramisu_x86_64_silvermont_stat
ic" (created by module "android.hardware.radio.ims.media-V1-ndk-generator" (crea
ted by module "android.hardware.radio.ims.media_interface")): (native:vendor:vnd
k) should not link to "android.hardware.radio.data-V2-ndk" (native:vendor): VNDK
-core must only depend on VNDK-core or VNDK-SP
```

Bug: 227979452
Test: Build
Change-Id: Ie3d964c09598ec6efd863c561c314bad7cc7731d